server:
  shutdown: graceful
  connection-timeout: 10s
  tomcat:
    threads:
      max: 64
      min-spare: 16
    accept-count: 100
    max-connections: 2048
    keep-alive-timeout: 10s

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/daycan?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

jwt:
  custom:
    secretKey: ${JWT_SECRET_KEY}
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 604800000

app:
  aws:
    region: ${APP_AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${APP_S3_BUCKET}
    sns:
      topic-arn: arn:aws:sns:ap-northeast-2:869652444193:daycan-create-report
      enabled: true

springdoc:
  swagger-ui:
    path: /api
    persist-authorization: true
